### PR TITLE
Google docs

### PR DESCRIPTION
**Pull request by buttegab**
google.py and the gspread folder are all that need to be merged.

### CODE REVIEW

**Comment by ManickYoj** [comment]
Heads up @buttegab  and @bishiguro - This branch has merge conflicts. Can you rebase onto master or merge it in and push again?

**Comment by DakotaNelson** [comment]
@buttegab can you get this ready to roll by Monday night? I'd really like to have this fully functional in the official release Tuesday.

**Comment by DakotaNelson** [comment]
Also, @buttegab a few questions:
1. Why is there a google.py and googleDocs.py? Are they actually two different channels? If so, how?
2. Could you add some documentation in README.md? I'm really not sure how to use this thing.
3. How do the cells work? It looks like you can specify the cell to receive from, but not send to. What's the mechanic there?

**Comment by DakotaNelson** [comment]
Superseded by #77.

**Pull request closed without merging**
