### PR TITLE
Adding AES support

### PR DESCRIPTION
**Pull request by davinerd**
Adding AES CTR support thanks to scrypt.

To test:

```
echo "some data" | python screep send -e aes -c file -p '{"file": {"filename": "test.txt"}, "aes":{"key":"enckey"}}'
```

```
python screep receive -e aes -c file -p '{"file": {"filename": "test.txt"}, "aes":{"key":"enckey"}}'
```

### CODE REVIEW

**Comment by DakotaNelson** [comment]
This will resolve #53.

**Comment by DakotaNelson** [comment]
I'm getting an error on this right now:

```
[dnelson@blueharvest sneaky-creeper]$ echo "this should be encrypted - awesome!" | ./screep send -c tumblrText -e aes -p tumblr-config.json 
Traceback (most recent call last):
  File "./screep", line 332, in <module>
    sendData(channelName, encoded, params[channelName])
  File "./screep", line 234, in sendData
    chan.send(packet, params)
  File "/home/dnelson/projects/sneaky-creeper/channels/tumblrText.py", line 50, in send
    client.create_text(params['username'], state="private", slug=rand, title=rand, body=data)
  File "/home/dnelson/.local/lib/python2.7/site-packages/pytumblr/helpers.py", line 44, in add_dot_tumblr
    return fn(*args, **kwargs)
  File "/home/dnelson/.local/lib/python2.7/site-packages/pytumblr/__init__.py", line 301, in create_text
    return self._send_post(blogname, kwargs)
  File "/home/dnelson/.local/lib/python2.7/site-packages/pytumblr/__init__.py", line 505, in _send_post
    return self.send_api_request("post", url, params, valid_options)
  File "/home/dnelson/.local/lib/python2.7/site-packages/pytumblr/__init__.py", line 538, in send_api_request
    return self.request.post(url, params, files)
  File "/home/dnelson/.local/lib/python2.7/site-packages/pytumblr/request.py", line 59, in post
    resp, content = client.request(url, method="POST", body=urllib.urlencode(params))
  File "/home/dnelson/.local/lib/python2.7/site-packages/oauth2/__init__.py", line 660, in request
    parameters=parameters, body=body, is_form_encoded=is_form_encoded)
  File "/home/dnelson/.local/lib/python2.7/site-packages/oauth2/__init__.py", line 573, in from_consumer_and_token
    is_form_encoded=is_form_encoded)
  File "/home/dnelson/.local/lib/python2.7/site-packages/oauth2/__init__.py", line 350, in __init__
    v = to_unicode_optional_iterator(v)
  File "/home/dnelson/.local/lib/python2.7/site-packages/oauth2/__init__.py", line 138, in to_unicode_optional_iterator
    return [ to_unicode(e) for e in l ]
  File "/home/dnelson/.local/lib/python2.7/site-packages/oauth2/__init__.py", line 106, in to_unicode
    raise TypeError('You are required to pass either a unicode object or a utf-8 string here. You passed a Python string object which contained non-utf-8: %r. The UnicodeDecodeError that resulted from attempting to interpret it as utf-8 was: %s' % (s, le,))
TypeError: You are required to pass either a unicode object or a utf-8 string here. You passed a Python string object which contained non-utf-8: 'a b scrypt\x00\x0e\x00\x00\x00\x08\x00\x00\x00\x01#]5\xfb\x90cJ$\xaf9\xaa\\\xfdv\xac\xdc9#)\thp\xd8\xf5\xb1\t\x10\xbf\x08\xa8\xac\xac\xacP\xae\x9b\xbfU;\\\xa4>\x94\x88\x9cMt\xb6\xf0>&\x15\xc5\xe3\xbb\x1a\x9e\xe6\x94\x1a^U\x84\x07\x89\xa6\xca\x8e\'WY\xc9Inz\xd0\xb6\xf2Q (\xc5\x99Pw\x86\x19p\x04\\\xb4\xc7\xfd=\x04\xcf}\xef\n[6\xc5\xf1\xde\xe7$\x7f\x94?U\xaaC\x95\xa83!\x95\\H\xf87&K!\xc1J:\x0el\xdc\\\xcd\x14\xccf\xe5\x1e\x16m\x9b\xa4\xc1gP(D\xff"'. The UnicodeDecodeError that resulted from attempting to interpret it as utf-8 was: 'utf8' codec can't decode byte 0xfb in position 23: invalid start byte
```

It looks like some of the channels (at least Tumblr) require encoding - which hasn't been an issue since we've been passing text before. I'll try to figure out a good way to make sure everything is safely encoded.

**Comment by DakotaNelson** [comment]
I've made the required changes (just a b64 encoding) in 83914b608e89e8dd05f3342c7c92b4e2ebccfdc6 - @davinerd if you could take a look and update this PR I think we'll be good to go! :+1:

**Comment by davinerd** [comment]
I don't think I should add the base64 encoding to the AES encoder.
AES encoder is what the name stand for: AES.

If Tumblr or other channels require b64, then the encoding should be done on the channel module, not in the encoder.
It's weird to use AES encoder and receive a b64 output, isn't it?

**Comment by DakotaNelson** [comment]
The issue is that AES outputs binary, and nearly every channel requires text input.

I think it makes sense to standardize channel input as utf-8 text (even if the text doesn't mean anything) rather than force the user to know what encoders output what, and what channels require what.

**Comment by davinerd** [comment]
As you said, "standardize" the channel input is something that should be done at channel level. What if a channel doesn't require b64 (es. 'file')? The code will start being clunky.

Also, it's not about the user that has to decide what encoder outputs what and what channel requires what, since:
- encoder output is in the name: b64 outputs b64, aes outputs encrypted text, rsa outputs encrypted text, etc etc.
- channel requirement is made by the developer, not the user, so the developer should knows which data a channel expect.

Finally, I still think that having a module that encrypt in AES outputting b64 breaks some 'best practices'.
But since it's your project, it's your call to specify the design.

If you still think it's worth done your way, I'll add the b64 encoding to the AES encoder.

**Comment by DakotaNelson** [comment]
I agree with you that outputting b64 isn't ideal, but it's not b64 that we want - it's text, and b64 is the only way to get there.

It's not a matter of b64 outputting b64 and AES outputting AES - it's a matter of b64 outputting text and AES outputting a string of bytes.

I'm definitely open to suggestions on what the correct layer of abstraction is, but I think forcing channels to do encoding (if, i.e., AES data is passed to tumblr, tumblr would have to b64 encode the output - there's no way around that) introduces problems, because then the channel has to be able to signal to the recipient that it encoded the input so the recipient can do the proper decoding.

The other option I see is to force the user to manually b64 encode the output of _certain_ encoders when using _certain_ channels, and that seems like too heavy a burden to place on the user - to  have to know what works with what - when we could handle it automatically.

**Pull request closed without merging**
