### PR TITLE
Refactor sneaky-creeper as a library

### PR DESCRIPTION
**Pull request by DakotaNelson**
@davinerd laid the foundation for using sneaky-creeper as a library, and it's awesome!

### CODE REVIEW

**Comment by DakotaNelson** [comment]
TODO before merging this:
- [x] Test Twitter ( @bishiguro or @buttegab, it would be good if you could take a look and make sure everything is good to go)
- [x] Convert Soundcloud to the new format and test it out ( @byronwasti can you do this?)
- [ ] Ideally write some more tests

**Comment by davinerd** [comment]
hey @DakotaNelson , do you have an update on this?
I think it can be merged :)

**Comment by DakotaNelson** [comment]
We're still waiting on checklist box number two above - I've been bothering @byronwasti to get Soundcloud fixed, to no avail. I'll try to carve out some time to take a look at it myself as soon as possible.

**Comment by DakotaNelson** [comment]
Holy crap, this is it! Going to go ahead and merge this is. Fantastic work, everyone - this is awesome!

**Pull request merged**
